name: 'Automatic Package Version Bump'
description:
  'Automatically bump the package version following semantic versioning based on
  the type from the PR title'
author: 'David Velásquez'

inputs:
  patches:
    description: 'List of patches types'
    default: 'fix, docs, style, refactor, perf, test, chore, build, ci, revert'
  minor:
    description: 'List of minor types'
    default: 'feat'
  major:
    description: 'List of major types'
    default: '!'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: arrow-up-circle
  color: green
