name: Bump package version
on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read

jobs:
  bump:
    if: github.event.pull_request.merged == true
    name: Bump package version
    runs-on: ubuntu-latest

    permissions:
      contents: write
      statuses: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GB_TOKEN }}
      - name: Bump to next version
        uses: ./
        with:
          minor: 'feat, feature'
