name: Bump package version
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump to next version
        uses: ./
