name: Bump package version
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump to next version
        uses: ./
